### ISSUE TITLE
pip install fails if executed globally

### ISSUE THREAD

**Issue by diegoperini** [rafpyprog/ImageSoup#2]
I wanted to experiment with the library and tried to install it without `virtualenv`, the result was an error like below.

```
mypc:Desktop $ pip install imagesoup
Collecting imagesoup
  Using cached imagesoup-0.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fc/n3pcr4jd2vn3byw8znm9xmtc0000gn/T/pip-build-ZXQMxl/imagesoup/setup.py", line 15, in <module>
        with open(os.path.join(here, 'imagesoup', '__version__.py'), 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fc/n3pcr4jd2vn3byw8znm9xmtc0000gn/T/pip-build-ZXQMxl/imagesoup/
```

Below is my dev machine info.

```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
```

**Comment by Leustad** [comment]
I can say that `pip install ImageSoup`  globally works for me. 

OS: Windows 10 Enterprise
```bash
$ python --version
Python 3.4.4 
```
```
$ python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
>>>
```

**Comment by rafpyprog** [comment]
Thanks @diegoperini  and @Leustad. Both of you were right. The module was working on Python3 but not on Python2.7.  Solved!

**Comment by diegoperini** [comment]
Seems to be fixed. Thank you.
